rvm:
  - 1.8.7
  - 1.9.2
  - 2.0.0
  - 2.1.0
env:
  <% if ENV['TRAVIS_BUILD_NUMBER'] % 5 = 0 %> - DB=postgres <% end %>
  <% if ENV['TRAVIS_BUILD_NUMBER'] % 5 = 0 %> - DB=mysql <% end %>
  - DB=sqlite

before_script:
  - cp config/database.yml.travis config/database.yml
  - git submodule init
  - git submodule update
  - mysql -e 'create database concerto_test'
  - psql -c 'create database concerto_test' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

branches:
  only:
    - master

notifications:
  irc: "irc.freenode.org#concerto-dev"
  email:
    recipients:
      concerto-dev@googlegroups.com
    on_success: change
    on_failure: change
